### ISSUE TITLE
可以分享您训练用的数据集吗？

### ISSUE THREAD

**Issue by 785008180** [siriusdemon/tensorflow-ocr#3]
Sirius Demon您好:
        我是天津工业大学计算机学院的一名大四学生，目前正在做我的毕业设计，和您的项目一样都是关于tensorflow-ocr中文印刷体字符识别的。我仔细阅读和运行过您hackaway/projects/ocr/和siriusdemon/tensorflow-ocr路径下的两个程序，发现由于自己没有数据集而不能正常运行，我试着用@Chong Ruan在Chinese-Character-Recognition项目中提供的手写体中文字符数据集来测试您的程序，不过准确率只有20%左右，效果很不理想。
        您可以把您训练用的数据集给我参考一下，以便我建立自己的训练数据集吗？或者您可以介绍一下您产生数据集的方法吗？我承诺该项目只用于我的学习和科研，没有任何商业用途。如果您为产生数据集付出了大量精力，我也愿意为此支付一部分费用。
        等待您的回应。
        qq：785008180 
        e-mail：785008180@qq.com

**Comment by siriusdemon** [comment]
可以的。字符集是我自己生成的，我看看明天或者其他时候分享给您，最迟下周一。但我的模型只能识别比较正常的印刷体，没有针对倾斜，扭曲等变体进行训练。您或许可以自己生成。到时候我把相关的东西打包整理一下吧。https://github.com/chineseocr/chinese-ocr 这个仓库您可以参考下，据说可以识别任意长度的。加油！

**Comment by 785008180** [comment]
好的！非常感谢！！！

**Comment by siriusdemon** [comment]
已给您回复邮件。
