### ISSUE TITLE
论文

### ISSUE THREAD

**Issue by Crescentz** [siriusdemon/tensorflow-ocr#4]
作者你好，我在做OCR相关工作，找了很多资料发现很多事场景字符识别的论文。
都说 印刷体字符识别 准确率很高了，那应该在此方面有很多相关论文，可是。。。。我没找到太多，请问作者有没有几篇推荐的好论文

**Comment by siriusdemon** [comment]
https://paperswithcode.com/search?q=ocr

**Comment by Crescentz** [comment]
1.非常感谢您的回复，感谢提供这个网站，头一次知道，以前只是在谷歌学术和arxiv上搜论文
2.问题是很多OCR论文是 ‘自然场景文字识别’ ，我想问作者你的是关于 ‘印刷体文字识别’，这方面的论文感觉不太容易找，很多推荐都是sence ocr
3.可否分享您看过的关于 扫描or印刷文字的 论文，谢谢，如果没有，我会close掉。

**Comment by siriusdemon** [comment]
+ 印刷体识别比自然场景识别更容易，印刷体的数据集你也可以自己构建，所以这个已经被解决得差不多了。
+ 自然场景的OCR，大部分也是印刷体，只是它可能是倾斜的～所以这是自然场景的难处。
+ 所以，如果你可以搞定自然场景OCR，印刷体当然不在话下。 Good Time!

**Comment by Crescentz** [comment]
感谢，我了解到的合成的有Synthetic Word Dataset和Caffe-ocr中文合成数据，但是没有找到关于合成扫描件或者正片PDF图片的 工具or数据集，您有了解过不，不胜感激

**Comment by siriusdemon** [comment]
这个不了解哦～

祝愿您可以尽快找到解决方案～
